iptables -A Mode_input-dns_dhcp_pc -p udp --dport 67:68 --sport 67:68 -j ACCEPT
iptables -A Mode_input-dns_dhcp_pc -p udp --dport 53 -j ACCEPT
iptables -A Mode_input-dns_dhcp_pc -p tcp --dport 53 -j ACCEPT
iptables -A Mode_input-dns_dhcp_pc -p tcp --dport 80 -j ACCEPT
iptables -A Mode_input-dns_dhcp_pc -m state --state ESTABLISHED,RELATED -j ACCEPT
