#nom;ip;estat
vlan_Admin;10.0.1.1/24;DESACTIVAT;
vlan_DMZ;10.0.2.1/24;DESACTIVAT;
vlan3;10.0.3.1/24;DESACTIVAT;
vlan4;10.0.4.1/24;DESACTIVAT;
vlan10;10.0.10.1/24;DESACTIVAT;
WIFI;10.0.100.1/24;DESACTIVAT;
