#vlan;id;forward;input;
vlan_Admin;1;desconnectar;connectar;
vlan_DMZ;2;aillar;desconnectar;
vlan3;3;connectar_regles_propies;connectar_regles_propies;
vlan4;4;desconnectar;desconnectar;
WIFI;4095;desconnectar;desconnectar;
vlan10;10;connectar;desconnectar;
wg-routers;4094;desconnectar;desconnectar;
wg-users;4093;desconnectar;desconnectar;
