DIR=/usr/local
DIR_PROJECTE=JSBach
DIR_CONF=conf
DIR_SCRIPTS=scripts
DIR_SYSTEM=system
DIR_CGI=cgi-bin
FUNCIONS=funcions
SERVEIS=serveis.conf
ACTIVAT=ACTIVAT
DESACTIVAT=DESACTIVAT
DESCONFIGURAT=DESCONFIGURAT
IFWAN_CONF=ifwan.conf
BRIDGE_CONF=bridge.conf
BRIDGE_IF=bridge_if.conf
BRIDGE_MAC_ADMIN=bridge_mac_admin.conf
DMZ_CONF=dmz.conf
IPTABLES_PORTS_WLS=iptables_Mode_forward_ports_wls.conf
IPTABLES_DOMINIS_WLS=iptables_Mode_forward_dominis_wls.conf
IPTABLES_PORTS_BLS=iptables_Mode_forward_ports_bls.conf
IPTABLES_DOMINIS_BLS=iptables_Mode_forward_dominis_bls.conf
IPTABLES_INPUT_WAN=regles_input_wan.conf
IPTABLES_INPUT_DNS_DHCP_PC=iptables_Mode_input_dns_dhcp_pc.conf
TALLAFOCS_VLANS=tallafocs-vlans.conf
SWITCHS=switchs.conf
SWITCHS_MACS_BLOCADES=switchs_macs_bloques.conf
SWITCHS_MACS_VLAN_ADMIN=switchs_macs_vlan_admin.conf
DHCP_CONF=dhcp.conf
DHCP_DNSMASQ_CONF=/etc/dnsmasq.conf
WIFI_DHCP_CONF=wifi_dhcp.conf
WIFI_HOSTAPD_CONF=wifi_hostapd.conf
WIFI_CONF=wifi.conf
PORTAL_CAPTIU_USUARIS=portal_captiu_usuaris.conf
PORTAL_CAPTIU_WWW=portal_captiu
PORTAL_CAPTIU_LANS=portal_captiu_lans.conf
VPN_WG_CONF=vpn_wg.conf
VPN_WG_LANS=vpn_wg_lans.conf
PORTMIRROR_CONF=portmirror.conf
CSS_CGI_BIN=css.text


