VPN_WG_USUARIS=vpn_wg-usuaris.conf
VPN_WG_ROUTERS=vpn_wg-routers.conf
VPN_WG_MODE=PRINCIPAL
vpn_wg_routers_fitxer_conf=/etc/wireguard/wg-routers.conf
vpn_wg_users_fitxer_conf=/etc/wireguard/wg-users.conf
vpn_wg_int_router=wg-routers
vpn_wg_int_users=wg-users
vpn_wg_port_router=51820
vpn_wg_port_users=51821
vpn_wg_ip_router=10.200.0.1
vpn_wg_ip_routers_mascara=24
vpn_wg_routers_public_key=9R9DedQjdmVPBGHthn29KeKzkpK7bEoB4NAusDimZDc=
vpn_wg_routers_private_key=AGpDrrPshsaLxt1CeuQSNcqfXsTWbh6wKHghG6iEY34=
vpn_wg_routers_allowed_ips=10.0.3.0/24,10.0.4.0/24,
vpn_wg_ip_users=10.201.0.1
vpn_wg_ip_users_mascara=24
vpn_wg_users_public_key=ovxboo/kav/pbY2XXlHV8gox2r4T/NYre6nZl5UoUGA=
vpn_wg_users_private_key=WKVjkBuspFxQbArSxUTjM3XxsoToHuXeOd4lbRVinUs=
vpn_wg_users_allowed_ips=10.0.4.0/24,