#!/bin/bash

source /usr/local/JSBach/conf/variables.conf

while read ordre; do
    if [[ -n $ordre ]]; then

        Comando=$(echo $ordre | awk '{print $1}')
        Arguments=$(echo $ordre | awk '{for (i=2; i<=NF; ++i)  printf $i " " }')

        case "$Comando" in
            "ifwan")
                $DIR/$DIR_PROJECTE/$DIR_SCRIPTS/ifwan $Arguments
                ;;
            "enrutar")
                $DIR/$DIR_PROJECTE/$DIR_SCRIPTS/enrutar $Arguments
                ;;
            "bridge")
                $DIR/$DIR_PROJECTE/$DIR_SCRIPTS/bridge $Arguments
                ;;
            "tallafocs")
                $DIR/$DIR_PROJECTE/$DIR_SCRIPTS/tallafocs $Arguments
                ;;
            "dmz")
                $DIR/$DIR_PROJECTE/$DIR_SCRIPTS/dmz $Arguments
                ;;
            "switchs")
                $DIR/$DIR_PROJECTE/$DIR_SCRIPTS/switchs $Arguments
                ;;
            "dhcp")
                $DIR/$DIR_PROJECTE/$DIR_SCRIPTS/dhcp $Arguments
                ;;
            "wifi")
                $DIR/$DIR_PROJECTE/$DIR_SCRIPTS/wifi $Arguments
                ;;
            "portal_captiu")
                $DIR/$DIR_PROJECTE/$DIR_SCRIPTS/portal_captiu $Arguments
                ;;
            "vpn_wg")
                $DIR/$DIR_PROJECTE/$DIR_SCRIPTS/vpn_wg $Arguments
                ;;
            "vpn_wg_client")
                $DIR/$DIR_PROJECTE/$DIR_SCRIPTS/vpn_wg_client $Arguments
                ;;
            "portmirror")
                $DIR/$DIR_PROJECTE/$DIR_SCRIPTS/portmirror $Arguments
                ;;
            *)
                echo "CLI Error, arguments [ifwan, enrutar, bridge, tallafocs, dmz, switchs, dhcp, wifi, vpn_wg, vpn_wg_client, portmirror]"
                ;;
        esac
    fi

    echo "final"
done
