#!/bin/bash

source /usr/local/JSBach/conf/variables.conf
source $DIR/$PROJECTE/$DIR_CONF/$CONF_IFWAN

######################################################################
###  Funcions
######################################################################

fnc_iniciar()
{

	if [ "$(fnc_estat)" == "$ACTIVAT" ]
	then
		echo "Ja esta activa"
		exit 1
	fi
	
	case "$IFW_MODE" in
	  "dhcp")
	    dhcpcd $IFW_IFWAN
	    ;;
	  "manual")
	    ip a a $IFW_IP/$IFW_MASC dev $IFW_IFWAN
	    ip l s dev $IFW_IFWAN up
	    ip r a default via $IFW_PE
	    if grep "#DNS=" /etc/systemd/resolved.conf;
	    then
	    	sed -i 's/#DNS=/DNS='$IFW_S_DNS'/g' /etc/systemd/resolved.conf
	    fi
	    
	    if ! grep "DNS=$IFW_S_DNS" /etc/systemd/resolved.conf;
	    then
	    	sed -i 's/^DNS=.*/DNS='$IFW_S_DNS'/g' /etc/systemd/resolved.conf
	    fi
	    systemctl restart systemd-resolved	
	    ;; 
	  *)
	    echo "ERROR al iniciar o dhcp o manual"
	    ;;
	esac
}

fnc_aturar()
{	
	# Check if already stopped
	if [ "$(fnc_estat)" == "$DESACTIVAT" ]; then
		echo "Ja està parada"
		exit 0
	fi

	case "$IFW_MODE" in
	  "dhcp")
	    echo "$IFW_MODE desactivant"
	    dhcpcd -k $IFW_IFWAN
	    ;;
	  "manual")
	    echo "$IFW_MODE desactivant"
	    ip a d $IFW_IP/$IFW_MASC dev $IFW_IFWAN
	    ip l s dev $IFW_IFWAN down
	    ;; 
	  *)
	    echo "ERROR al aturar o dhcp o manual"
	    ;;
	esac
}


fnc_configurar()
{	
	if [[ "$1" == "mostrar" ]] then
		echo $IFW_MODE $IFW_IFWAN $IFW_IP $IFW_MASC $IFW_PE $IFW_S_DNS
	else
		fnc_aturar	
		(
			echo IFW_MODE=$1 
			echo IFW_IFWAN=$2
			echo IFW_IP=$( echo $3 | cut -d'/' -f1 )
			echo IFW_MASC=$( echo $3 | cut -d'/' -f2 )
			echo IFW_PE=$4
			echo IFW_S_DNS=$5
		) >  $DIR/$PROJECTE/$DIR_CONF/$CONF_IFWAN
		
		echo "Configuracio guardada i targeta aturada"
	fi
}


fnc_estat()
{	
	if nslookup google.com > /dev/null 2>&1 ; then
		# Get IP address
		IP_ADDR=$(ip addr show $IFW_IFWAN 2>/dev/null | grep 'inet ' | awk '{print $2}' | cut -d'/' -f1)
		
		if [ -n "$IP_ADDR" ]; then
			echo "<span style='color: green; font-weight: bold;'>✓ ACTIVAT</span><br>"
			echo "IP: <strong>$IP_ADDR</strong><br>"
			echo "Dev: <strong>$IFW_IFWAN</strong>"
		else
			echo "<span style='color: green; font-weight: bold;'>ACTIVAT</span> (sense IP)"
		fi
	else
		echo "<span style='color: red; font-weight: bold;'>✗ DESACTIVAT</span>"
	fi
	    
}


######################################################################
###  MAIN
######################################################################

MSG="falta [iniciar, aturar, configurar ,estat]"

# Comprovem que hi hagi almenys un argument (la opció)
if [ $# -lt 1 ]; then
  echo "$MSG"
  exit 1
fi

OPCIO_1=$1
shift

# Fem switch IFW_PEr executar la funció que toca
case "$OPCIO_1" in
  iniciar)
    fnc_iniciar  $@
    ;;
  aturar)
    fnc_aturar	$@
    ;; 
  configurar) 
    fnc_configurar $@
    ;;
  estat) 
    fnc_estat $@
    ;;
  *)
    echo "$MSG"
    ;;
esac


