#!/bin/bash

source /usr/local/JSBach/conf/variables.conf

######################################################################
###  Funcions
######################################################################

fnc_estat() {
	if [ ! -f "$DIR/$PROJECTE/$DIR_CONF/$SWITCHS" ]; then
		return
	fi

	grep -v '#' "$DIR/$PROJECTE/$DIR_CONF/$SWITCHS" | while read linia; do
		# Robust field extraction
		nom=$(echo "$linia" | cut -d';' -f1)
		# Clean IP (remove spaces/newlines)
		ip=$(echo "$linia" | cut -d';' -f2 | tr -d '[:space:]')
		
		# Ping with 2 packets, 2 second timeout, no DNA lookup (-n)
		# Using full path /usr/bin/ping
		if /usr/bin/ping -c 2 -W 2 -n "$ip" >/dev/null 2>&1; then
		  echo "$nom $ip FUNCIONA"
		else
		  echo "$nom $ip NO_RESPON"
		fi
	done
}

fnc_taula_mac() {
    local IP="$1"
    local USER="$2"
    local PASS="$3"
    local PROTOCOL="$4"  # ssh or telnet

    # Default to SSH if not specified
    if [ -z "$PROTOCOL" ]; then PROTOCOL="ssh"; fi

    # Determine Spawn Command
    if [ "$PROTOCOL" == "telnet" ]; then
        SPAWN_CMD="spawn telnet $IP"
    else
        SPAWN_CMD="spawn ssh -o StrictHostKeyChecking=no $USER@$IP"
    fi

    # Needs 'expect' package installed
    expect << EOF | sed -n '/show mac address-table/,$p' | sed '1d' | sed '/#\|>/,$d'
set timeout 10

$SPAWN_CMD

expect {
    "*assword:*" {
        send "$PASS\r"
    }
    "Login:" {
        send "$USER\r"
        expect "*assword:*"
        send "$PASS\r"
    }
}

# Wait for initial prompt (>)
expect ">"
send "enable\r"

# Enable password prompt might be needed depending on device config
# Usually matches "Password:" again
expect {
    "*assword:*" {
        send "$PASS\r"
        # Wait for privileged prompt (#)
        expect "#"
    }
    "#" {
        # Already privileged
    }
}

send "show mac address-table\r"

# Wait for prompt again
expect "#"
send "exit\r"

expect eof
EOF
}

fnc_configurar() {
	if [ $# -lt 1 ]; then
		echo "Error falta eliminar|afegir"
		exit 1
	fi
	
	OPCIO_1=$1
	shift

	case "$OPCIO_1" in
		eliminar)
			if [ $# -lt 2 ]; then
				echo "Error falta nom_switch ip_switch "
				exit 1
			fi
			Nom="$1"
			IP="$2"
			# Remove line starting with Nom;IP;
			sed -i "/^${Nom};${IP};/d" "$DIR/$PROJECTE/$DIR_CONF/$SWITCHS"
			echo "Deleted $Nom ($IP)"
			;;
		afegir)
			if [ $# -lt 4 ]; then
				echo "Error falta nom_switch ip_switch user pass [protocol]"
				exit 1
			fi
			# Use default 'ssh' if protocol ($5) is missing
			PROTO="${5:-ssh}"
			
			# Append to file: nom;ip;user;pass;protocol
			echo "$1;$2;$3;$4;$PROTO" >> "$DIR/$PROJECTE/$DIR_CONF/$SWITCHS"
			echo "Added $1 ($2) via $PROTO"
			;;
		*)
			echo "$MSG"
			;;
	esac
}


######################################################################
###  MAIN
######################################################################

MSG="falta [estat, configurar, taula_mac ]"


# Check at least one argument
if [ $# -lt 1 ]; then
	echo "$MSG"
	exit 1
fi

OPCIO_1=$1
shift

case "$OPCIO_1" in
	estat)
		fnc_estat $@
		;;
	configurar)
		fnc_configurar $@
		;;
	taula_mac)
		# Pass all remaining arguments to function (IP USER PASS PROTOCOL)
		fnc_taula_mac "$@"
		;;	
	*)
		echo "$MSG"
		;;
esac
