#!/bin/bash

source /usr/local/JSBach/conf/variables.conf
source $DIR/$DIR_PROJECTE/$DIR_SCRIPTS/$FUNCIONS

######################################################################
###  Funcions
######################################################################

fnc_iniciar() {
    fnc_aturar > /dev/null 2>&1

    ######################################################################
    ###  FORWARD
    ######################################################################
    echo "Iniciant tallafocs"
    
    fnc_Modes_crea_regles_forward

    for linia in $(fnc_buscar_Lans | grep -v '#'); do
        vid=$(echo "$linia" | cut -d';' -f2)
        nom=$(echo "$linia" | cut -d';' -f1)
        ip=$(echo "$linia" | cut -d';' -f3)
        iptables -N Forward-$nom
        if [[ "$vid" == "1" ]]; then
            iptables -A FORWARD -d $ip -j Forward-$nom
        else
            iptables -A FORWARD -s $ip -j Forward-$nom
        fi

        #iptables -N regles_forward_$nom
        if [ ! -f "$DIR/$DIR_PROJECTE/$DIR_CONF/regles_forward_$nom.conf" ]; then
            touch "$DIR/$DIR_PROJECTE/$DIR_CONF/regles_forward_$nom.conf"
            chmod +rx "$DIR/$DIR_PROJECTE/$DIR_CONF/regles_forward_$nom.conf"
        fi
    done

    fnc_aplica_regles_forward_vlans

    ######################################################################
    ###  INPUT
    ######################################################################

    ##### WAN
    {
        source $DIR/$DIR_PROJECTE/$DIR_CONF/$IFWAN_CONF
        iptables -N Input_wan
        iptables -A INPUT -i $IFW_IFWAN -j Input_wan

        regles_input_wan="$DIR/$DIR_PROJECTE/$DIR_CONF/$IPTABLES_INPUT_WAN"

        if [ ! -f "$regles_input_wan" ]; then
            touch "$regles_input_wan"
            chmod +rx "$regles_input_wan"
            echo "iptables -A Input_wan -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT" >> "$regles_input_wan"
            echo "iptables -A Input_wan -p icmp -j ACCEPT" >> "$regles_input_wan"
            echo "iptables -A Input_wan -m conntrack --ctstate NEW -j DROP" >> "$regles_input_wan"
        fi

        fnc_aplica_regles_input_wan
    }

    ##### VLANS i WIFI
    for linia in $(fnc_buscar_Lans | grep -v '#'); do
        vid=$(echo "$linia" | cut -d';' -f2)
        nom=$(echo "$linia" | cut -d';' -f1)
        ip=$(echo "$linia" | cut -d';' -f3)
        iptables -N Input-$nom
        iptables -A INPUT -s $ip -j Input-$nom
    done

    sed -i 's/^tallafoc;.*/tallafoc;ACTIVAT/' $DIR/$DIR_PROJECTE/$DIR_CONF/$SERVEIS
}

fnc_aplica_regles_forward_vlans() {
    for linia in $(fnc_buscar_Lans | grep -v '#'); do
        vid=$(echo "$linia" | cut -d';' -f2)
        nom=$(echo "$linia" | cut -d';' -f1)
        CONFIGURACIO=$(grep "$vid;" "$DIR/$DIR_PROJECTE/$DIR_CONF/$TALLAFOCS_VLANS" | cut -d';' -f3)
        case "$CONFIGURACIO" in
            "aillar")
                fnc_configurar aillar $vid
                ;;
            "connectar")
                fnc_configurar connectar $vid
                ;;
            "desconnectar")
                fnc_configurar desconnectar $vid
                ;;
            "connectar_regles_propies")
                fnc_configurar connectar_regles_propies $vid
                ;;
            "")
                echo "$nom;$vid;desconnectar">>$DIR/$DIR_PROJECTE/$DIR_CONF/$TALLAFOCS_VLANS
                fnc_configurar desconnectar $vid
                ;;
        esac
    done
}

fnc_Modes_crea_regles_forward() {
    #aillar
    if iptables -nvL | grep Mode_forward_aillar 1>&2; then
        iptables -F Mode_forward_aillar
    else
        iptables -N Mode_forward_aillar
    fi
    iptables -A Mode_forward_aillar -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
    iptables -A Mode_forward_aillar -p udp -m conntrack --ctstate NEW -j DROP
    iptables -A Mode_forward_aillar -p tcp -m conntrack --ctstate NEW -j DROP
    iptables -A Mode_forward_aillar -j DROP

    #ports_wls
    if iptables -nvL | grep Mode_forward_ports_wls 1>&2; then
        iptables -F Mode_forward_ports_wls
    else
        iptables -N Mode_forward_ports_wls
    fi

    for linia in $(grep -v '#' "$DIR/$DIR_PROJECTE/$DIR_CONF/$IPTABLES_PORTS_WLS"); do
        protocol=$(echo "$linia" | cut -d';' -f1)
        num_port=$(echo "$linia" | cut -d';' -f2)
        iptables -A Mode_forward_ports_wls -p $protocol --dport $num_port -j ACCEPT
    done
    

    #dominis_wls
    if iptables -nvL | grep Mode_forward_dominis_wls 1>&2; then
        iptables -F Mode_forward_dominis_wls
    else
        iptables -N Mode_forward_dominis_wls
    fi

    for linia in $(grep -v '#' "$DIR/$DIR_PROJECTE/$DIR_CONF/$IPTABLES_DOMINIS_WLS"); do
        ip=$(echo "$linia" | cut -d';' -f1)
        iptables -A Mode_forward_dominis_wls -d $ip -j ACCEPT
    done
    
    #ports_bls
    if iptables -nvL | grep Mode_forward_ports_bls 1>&2; then
        iptables -F Mode_forward_ports_bls
    else
        iptables -N Mode_forward_ports_bls
    fi

    for linia in $(grep -v '#' "$DIR/$DIR_PROJECTE/$DIR_CONF/$IPTABLES_PORTS_BLS"); do
        protocol=$(echo "$linia" | cut -d';' -f1)
        num_port=$(echo "$linia" | cut -d';' -f2)
        iptables -A Mode_forward_ports_bls -p $protocol --dport $num_port -j DROP
    done
    

    #dominis_bls
    if iptables -nvL | grep Mode_forward_dominis_bls 1>&2; then
        iptables -F Mode_forward_dominis_bls
    else
        iptables -N Mode_forward_dominis_bls
    fi

    for linia in $(grep -v '#' "$DIR/$DIR_PROJECTE/$DIR_CONF/$IPTABLES_DOMINIS_BLS"); do
        ip=$(echo "$linia" | cut -d';' -f1)
        iptables -A Mode_forward_dominis_bls -d $ip -j DROP
    done
}

fnc_Modes_mostrar_cadenes_forward() {
    iptables -L | grep '^Chain' | grep Mode |  awk '{print $2}'
}

fnc_Modes_eliminar_cadenes() {
    for cadena in $(fnc_Modes_mostrar_cadenes_forward); do
        iptables -F $cadena
    done
}

fnc_aplica_regles_input_wan() {
    while IFS= read -r linia; do
        # Saltar línies buides i comentaris
        [[ -z "$linia" || "$linia" =~ ^# ]] && continue

        eval "$linia"
    done < "$DIR/$DIR_PROJECTE/$DIR_CONF/$IPTABLES_INPUT_WAN"
}

fnc_aplicar_regles_propies_forward() {
    while IFS= read -r linia; do
        # Saltar línies buides i comentaris
        [[ -z "$linia" || "$linia" =~ ^# ]] && continue

        eval "$linia"
    done < "$DIR/$DIR_PROJECTE/$DIR_CONF/regles_forward_$1.conf"
}

fnc_aturar() {
    echo "Aturar tallafocs"
    iptables -F
    iptables -X
    iptables -P FORWARD ACCEPT
    iptables -P INPUT ACCEPT
    iptables -P OUTPUT ACCEPT

    resultat=$($DIR/$DIR_PROJECTE/$DIR_SCRIPTS/enrutar estat)

    # Comprovem si conté la paraula "ACTIVAT"
    echo "$resultat" | grep -q "$ACTIVAT"

    if [ $? -eq 0 ]; then
        iptables -t nat -F
        iptables -t nat -X
        $DIR/$DIR_PROJECTE/$DIR_SCRIPTS/enrutar iniciar > /dev/null 2>&1
    else
        iptables -t nat -F
        iptables -t nat -X
    fi

    sed -i 's/^tallafoc;.*/tallafoc;DESACTIVAT/' $DIR/$DIR_PROJECTE/$DIR_CONF/$SERVEIS
}


fnc_configurar() {
    ARG_1=$1
    shift

    # Fem switch per executar la funció que toca
    case "$ARG_1" in
        aillar)
            if [ "$#" -lt 1 ]; then
                echo "Error falta vlan"
                exit 1
            fi

            if ! $(fnc_validar_vlan_id $1) || ! $(fnc_existeix_vlan_id $1); then
                echo "Error no existeix vlan $1"
                exit 1
            fi

            linia=$(fnc_buscar_Lans | grep ";$1;")
            nom=$(echo $linia | cut -d';' -f1)
            vid=$(echo $linia | cut -d';' -f2)
            if [ -z "$nom" ]; then
                echo "Error no existeix vlan $1"
            else
                iptables -F Forward-$nom
                iptables -A Forward-$nom -j Mode_forward_aillar
                sed -i "s/$nom;$vid;.*$/$nom;$vid;aillar/g" "$DIR/$DIR_PROJECTE/$DIR_CONF/$TALLAFOCS_VLANS"
            fi
            ;;
        desconnectar)
            if [ "$#" -lt 1 ]; then
                echo "Error falta vlan"
                exit 1
            fi

            if ! $(fnc_validar_vlan_id $1) || ! $(fnc_existeix_vlan_id $1); then
                echo "Error no existeix vlan $1"
                exit 1
            fi

            linia=$(fnc_buscar_Lans | grep ";$1;")
            nom=$(echo $linia | cut -d';' -f1)
            vid=$(echo $linia | cut -d';' -f2)
            if [ -z "$nom" ]; then
                echo "Error no existeix vlan $1"
            else
                iptables -F Forward-$nom
                iptables -A Forward-$nom -j DROP
                sed -i "s/$nom;$vid;.*$/$nom;$vid;desconnectar/g" "$DIR/$DIR_PROJECTE/$DIR_CONF/$TALLAFOCS_VLANS"
            fi
            ;;
        connectar)
            if [ "$#" -lt 1 ]; then
                echo "Error falta vlan"
                exit 1
            fi

            if ! $(fnc_validar_vlan_id $1) || ! $(fnc_existeix_vlan_id $1); then
                echo "Error no existeix vlan $1"
                exit 1
            fi

            linia=$(fnc_buscar_Lans | grep ";$1;")
            nom=$(echo $linia | cut -d';' -f1)
            if [ -z "$nom" ]; then
                echo "Error no existeix vlan $1"
            else
                iptables -F Forward-$nom
                sed -i "s/$nom;$vid;.*$/$nom;$vid;connectar/g" "$DIR/$DIR_PROJECTE/$DIR_CONF/$TALLAFOCS_VLANS"
            fi
            ;;
        desconnectar_input)
            if [ "$#" -lt 1 ]; then
                echo "Error falta vlan"
                exit 1
            fi

            if ! $(fnc_validar_vlan_id $1) || ! $(fnc_existeix_vlan_id $1); then
                echo "Error no existeix vlan $1"
                exit 1
            fi

            linia=$(fnc_buscar_Lans | grep ";$1;")
            nom=$(echo $linia | cut -d';' -f1)
            vid=$(echo $linia | cut -d';' -f2)
            if [ -z "$nom" ]; then
                echo "Error no existeix vlan $1"
            else
                iptables -F Input-$nom
                iptables -A Input-$nom -j DROP
            fi
            ;;
        connectar_input)
            if [ "$#" -lt 1 ]; then
                echo "Error falta vlan"
                exit 1
            fi

            if ! $(fnc_validar_vlan_id $1) || ! $(fnc_existeix_vlan_id $1); then
                echo "Error no existeix vlan $1"
                exit 1
            fi

            linia=$(fnc_buscar_Lans | grep ";$1;")
            nom=$(echo $linia | cut -d';' -f1)
            if [ -z "$nom" ]; then
                echo "Error no existeix vlan $1"
            else
                iptables -F Input-$nom
            fi
            ;;
        connectar_regles_propies)
            if [ "$#" -lt 1 ]; then
                echo "Error falta vlan"
                exit 1
            fi

            if ! $(fnc_validar_vlan_id $1) || ! $(fnc_existeix_vlan_id $1); then
                echo "Error no existeix vlan $1"
                exit 1
            fi

            linia=$(fnc_buscar_Lans | grep ";$1;")
            nom=$(echo $linia | cut -d';' -f1)
            vid=$(echo $linia | cut -d';' -f2)
            if [ -z "$nom" ]; then
                echo "Error no existeix vlan $1"
            else
                iptables -F Forward-$nom
                fnc_aplicar_regles_propies_forward $nom
                sed -i "s/$nom;$vid;.*$/$nom;$vid;connectar_regles_propies/g" "$DIR/$DIR_PROJECTE/$DIR_CONF/$TALLAFOCS_VLANS"
            fi
            ;;
        afegir_nova_regla)
            ############################################
            # Comprovació d'arguments
            ############################################
            if [ "$#" -lt 3 ]; then
                echo "Ús:"
                echo "  $0 <VNOM> <POSICIO> \"iptables -A Forward_VNOM ...\""
                exit 1
            fi

            if ! $(fnc_validar_vlan_nom $1) || ! $(fnc_existeix_vlan_nom $1); then
                echo "Error no existeix vlan $1"
                exit 1
            fi

            VNOM="$1"
            POSICIO="$2"
            shift 2
            REGLA_COMPLETA="$*"

            FITXER="$DIR/$DIR_PROJECTE/$DIR_CONF/regles_forward_$VNOM.conf"

            ############################################
            # Validació mínima de la regla
            ############################################
            if ! [[ "$REGLA_COMPLETA" =~ ^iptables[[:space:]]+-A[[:space:]]+Forward-$VNOM[[:space:]] ]]; then
                echo "Error: la regla ha de començar per:"
                echo "  iptables -A Forward-$VNOM"
                exit 1
            fi

            check_regla="${REGLA_COMPLETA/-A /-C }"

            $check_regla 2> /dev/null
            RET=$?

            if [ "$RET" -eq 2 ]; then
                echo "Regla MAL formada"
                exit 1
            fi

            ############################################
            # Crear fitxer si no existeix
            ############################################
            [ -f "$FITXER" ] || touch "$FITXER"
            chmod +rx "$FITXER"
            ############################################
            # Comptar regles reals
            ############################################
            NUM_LINIES=$(grep -v '^\s*$' "$FITXER" | grep -v '^#' | wc -l)

            ############################################
            # Validar posició
            ############################################
            if ! [[ "$POSICIO" =~ ^[0-9]+$ ]] || [ "$POSICIO" -le 0 ]; then
                POSICIO=$((NUM_LINIES + 1))
            elif [ "$POSICIO" -gt $((NUM_LINIES + 1)) ]; then
                POSICIO=$((NUM_LINIES + 1))
            fi

            ############################################
            # Inserir regla completa
            ############################################
            TMP="$(mktemp)"
            N=0
            INSERIDA=0

            while IFS= read -r LINIA; do
                if [[ -z "$LINIA" || "$LINIA" =~ ^[[:space:]]*# ]]; then
                    echo "$LINIA" >> "$TMP"
                    continue
                fi

                N=$((N + 1))

                if [ "$N" -eq "$POSICIO" ] && [ "$INSERIDA" -eq 0 ]; then
                    echo "$REGLA_COMPLETA" >> "$TMP"
                    INSERIDA=1
                fi

                echo "$LINIA" >> "$TMP"
            done < "$FITXER"

            if [ "$INSERIDA" -eq 0 ]; then
                echo "$REGLA_COMPLETA" >> "$TMP"
            fi

            mv "$TMP" "$FITXER"
            chmod +rx "$FITXER"

            ############################################
            # Sortida
            ############################################
            echo "✔ Regla inserida correctament"

            iptables -F Forward-$VNOM
            linia=$(fnc_buscar_Lans | grep "$VNOM;")
            vid=$(echo $linia | cut -d';' -f2)
            fnc_aplicar_regles_propies_forward $VNOM
            iptables -nvL Forward-$VNOM
            ;;
        afegir_nova_regla_wan)
            ############################################
            # Comprovació d'arguments
            ############################################
            if [ "$#" -lt 2 ]; then
                echo "Ús:"
                echo "  $0  <POSICIO> \"iptables -A Input_wan ...\""
                exit 1
            fi

            POSICIO="$1"
            shift 1
            REGLA_COMPLETA="$*"

            FITXER="$DIR/$DIR_PROJECTE/$DIR_CONF/$IPTABLES_INPUT_WAN"

            ############################################
            # Validació mínima de la regla
            ############################################
            echo "$REGLA_COMPLETA"
            if ! [[ "$REGLA_COMPLETA" =~ ^iptables[[:space:]]+-A[[:space:]]+Input_wan[[:space:]] ]]; then
                echo "Error: la regla ha de començar per:"
                echo "  iptables -A Input_wan "
                exit 1
            fi

            check_regla="${REGLA_COMPLETA/-A /-C }"

            $check_regla 2> /dev/null
            RET=$?

            if [ "$RET" -eq 2 ]; then
                echo "Regla MAL formada"
                exit 1
            fi

            ############################################
            # Crear fitxer si no existeix
            ############################################
            [ -f "$FITXER" ] || touch "$FITXER"
            chmod +rx "$FITXER"
            ############################################
            # Comptar regles reals
            ############################################
            NUM_LINIES=$(grep -v '^\s*$' "$FITXER" | grep -v '^#' | wc -l)

            ############################################
            # Validar posició
            ############################################
            if ! [[ "$POSICIO" =~ ^[0-9]+$ ]] || [ "$POSICIO" -le 0 ]; then
                POSICIO=$((NUM_LINIES + 1))
            elif [ "$POSICIO" -gt $((NUM_LINIES + 1)) ]; then
                POSICIO=$((NUM_LINIES + 1))
            fi

            ############################################
            # Inserir regla completa
            ############################################
            TMP="$(mktemp)"
            N=0
            INSERIDA=0

            while IFS= read -r LINIA; do
                if [[ -z "$LINIA" || "$LINIA" =~ ^[[:space:]]*# ]]; then
                    echo "$LINIA" >> "$TMP"
                    continue
                fi

                N=$((N + 1))

                if [ "$N" -eq "$POSICIO" ] && [ "$INSERIDA" -eq 0 ]; then
                    echo "$REGLA_COMPLETA" >> "$TMP"
                    INSERIDA=1
                fi

                echo "$LINIA" >> "$TMP"
            done < "$FITXER"

            if [ "$INSERIDA" -eq 0 ]; then
                echo "$REGLA_COMPLETA" >> "$TMP"
            fi

            mv "$TMP" "$FITXER"
            chmod +rx "$FITXER"

            ############################################
            # Sortida
            ############################################
            echo "✔ Regla inserida correctament"

            iptables -F Input_wan
            fnc_aplica_regles_input_wan
            iptables -nvL Input_wan
            ;;
        eliminar_regla)
            ############################################
            # Comprovació d'arguments
            ############################################
            if [ "$#" -lt 2 ]; then
                echo "Ús:"
                echo "  $0 <VNOM> <POSICIO regla a eliminar>"
                exit 1
            fi

            if ! $(fnc_validar_vlan_nom $1) || ! $(fnc_existeix_vlan_nom $1); then
                echo "Error no existeix vlan $1"
                exit 1
            fi

            VNOM="$1"
            POSICIO="$2"
            FITXER="$DIR/$DIR_PROJECTE/$DIR_CONF/regles_forward_$VNOM.conf"

            if [ ! -f "$FITXER" ]; then
                echo "ERROR no existeix regles_forward_$VNOM.conf"
            else
                sed -i "${POSICIO}d" "$FITXER"
                echo "Regla eliminada"
            fi

            iptables -F Forward-$VNOM
            linia=$(fnc_buscar_Lans | grep "$VNOM;")
            vid=$(echo $linia | cut -d';' -f2)
            fnc_aplicar_regles_propies_forward $VNOM
            iptables -nvL Forward-$VNOM
            ;;
        eliminar_regla_wan)
            ############################################
            # Comprovació d'arguments
            ############################################
            if [ "$#" -lt 1 ]; then
                echo "Ús:"
                echo "  $0 <POSICIO regla a eliminar>"
                exit 1
            fi

            POSICIO="$1"
            FITXER="$DIR/$DIR_PROJECTE/$DIR_CONF/$IPTABLES_INPUT_WAN"

            if [ ! -f "$FITXER" ]; then
                echo "ERROR no existeix $IPTABLES_INPUT_WAN"
            else
                sed -i "${POSICIO}d" "$FITXER"
                echo "Regla eliminada"
            fi

            iptables -F Input_wan
            fnc_aplica_regles_input_wan
            iptables -nvL Input_wan
            ;;
        afegir_port_wls)
            if [ "$#" -lt 2 ]; then
                echo "Ús:"
                echo "  $0 <PROTOCOL> <PORT>"
                exit 1
            fi

            PROTO="$1"
            PORT="$2"

            if ! fnc_validar_protocol "$PROTO"; then
                echo "Error: Protocol '$PROTO' no és vàlid."
                echo "Protocols vàlids: tcp, udp, icmp, arp, igmp, all"
                exit 1
            fi

            if ! fnc_validar_port "$PORT"; then
                echo "Error: El port '$PORT' no és vàlid."
                exit 1
            fi

            echo "$PROTO;$PORT;" >> "$DIR/$DIR_PROJECTE/$DIR_CONF/$IPTABLES_PORTS_WLS"
            fnc_Modes_eliminar_cadenes
            fnc_Modes_crea_regles_forward
            ;;
        eliminar_port_wls)
            if [ "$#" -lt 2 ]; then
                echo "Ús:"
                echo "  $0 <PROTOCOL> <PORT>"
                exit 1
            fi

            PROTO="$1"
            PORT="$2"
            sed -i "/^${PROTO};${PORT};$/d" "$DIR/$DIR_PROJECTE/$DIR_CONF/$IPTABLES_PORTS_WLS"
            fnc_Modes_eliminar_cadenes
            fnc_Modes_crea_regles_forward
            ;;
        
        afegir_port_bls)
            if [ "$#" -lt 2 ]; then
                echo "Ús:"
                echo "  $0 <PROTOCOL> <PORT>"
                exit 1
            fi

            PROTO="$1"
            PORT="$2"

            if ! fnc_validar_protocol "$PROTO"; then
                echo "Error: Protocol '$PROTO' no és vàlid."
                echo "Protocols vàlids: tcp, udp, icmp, arp, igmp, all"
                exit 1
            fi

            if ! fnc_validar_port "$PORT"; then
                echo "Error: El port '$PORT' no és vàlid."
                exit 1
            fi

            echo "$PROTO;$PORT;" >> "$DIR/$DIR_PROJECTE/$DIR_CONF/$IPTABLES_PORTS_BLS"
            fnc_Modes_eliminar_cadenes
            fnc_Modes_crea_regles_forward
            ;;
        eliminar_port_bls)
            if [ "$#" -lt 2 ]; then
                echo "Ús:"
                echo "  $0 <PROTOCOL> <PORT>"
                exit 1
            fi

            PROTO="$1"
            PORT="$2"
            sed -i "/^${PROTO};${PORT};$/d" "$DIR/$DIR_PROJECTE/$DIR_CONF/$IPTABLES_PORTS_BLS"
            fnc_Modes_eliminar_cadenes
            fnc_Modes_crea_regles_forward
            ;;
        afegir_dominis_wls)
            if [ "$#" -lt 1 ]; then
                echo "Ús:"
                echo "  $0 <DOMINI>"
                exit 1
            fi

            DOMINI="$1"

            echo "$DOMINI;" >> "$DIR/$DIR_PROJECTE/$DIR_CONF/$IPTABLES_DOMINIS_WLS"
            fnc_Modes_eliminar_cadenes
            fnc_Modes_crea_regles_forward
            ;;
        eliminar_dominis_wls)
            if [ "$#" -lt 1 ]; then
                echo "Ús:"
                echo "  $0 <DOMINI>"
                exit 1
            fi

            DOMINI="$1"
            sed -i "/^${DOMINI};$/d" "$DIR/$DIR_PROJECTE/$DIR_CONF/$IPTABLES_DOMINIS_WLS"
            fnc_Modes_eliminar_cadenes
            fnc_Modes_crea_regles_forward
            ;;
        
        afegir_dominis_bls)
            if [ "$#" -lt 1 ]; then
                echo "Ús:"
                echo "  $0 <DOMINI>"
                exit 1
            fi

            DOMINI="$1"

            echo "$DOMINI;" >> "$DIR/$DIR_PROJECTE/$DIR_CONF/$IPTABLES_DOMINIS_BLS"
            fnc_Modes_eliminar_cadenes
            fnc_Modes_crea_regles_forward
            ;;
        eliminar_dominis_bls)
            if [ "$#" -lt 1 ]; then
                echo "Ús:"
                echo "  $0 <DOMINI>"
                exit 1
            fi

            DOMINI="$1"
            sed -i "/^${DOMINI};$/d" "$DIR/$DIR_PROJECTE/$DIR_CONF/$IPTABLES_DOMINIS_BLS"
            fnc_Modes_eliminar_cadenes
            fnc_Modes_crea_regles_forward
            ;;        
        *)
            echo "Error  argumnets aillar,conectar, desconnectar, conectar-input, desconectar-input, connectar_port_wls,connectar_regles_propies,afegir_nova_regla,eliminar_regla,afegir_port_wls,eliminar_port_wls"
            ;;
    esac
}

fnc_mostrar() {
    ARG_1=$1
    shift

    # Fem switch per executar la funció que toca
    case "$ARG_1" in
        cadenes)
            fnc_Modes_mostrar_cadenes_forward
            ;;
        *)  
            echo "Error falta opcio cadenes"
            ;;
    esac
}

fnc_estat() {

    if [ $# -eq 0 ]; then
        if iptables -S | grep -q '^-A'; then
            echo "$ACTIVAT"
        else
            echo "$DESACTIVAT"
        fi
        echo " "
        echo MAIN
        iptables -nvL --line-numbers
        echo
        echo
        echo NAT
        iptables -t nat -nvL --line-numbers
        exit 1
    fi

    ARG_1=$1
    shift

    linia=$(fnc_buscar_Lans | grep ";$1;")
    nom=$(echo $linia | cut -d';' -f1)

    if [ -z $nom ]; then
        echo "Error no existeix $nom"
        exit 1
    fi

    # Fem switch per executar la funció que toca
    case "$ARG_1" in
        forward)
            fnc_estat_vlan Forward-$nom
            ;;
        input)
            fnc_estat_vlan Input-$nom
            ;;
        wan) ;;
        *)
            echo "Error falta forward,input"
            ;;
    esac
}

fnc_estat_vlan() {
    if [ $# -eq 0 ]; then
        echo "Error, falta nom de la vlan"
        exit 1
    fi

    cadena=$1
    vlan=$(echo $cadena | cut -d'-' -f2)
    num_rules=$(iptables -L Forward-"$vlan" -n --line-numbers | tail -n +3 | wc -l)
    first_rule=$(iptables -L Forward-"$vlan" -n --line-numbers | awk 'NR==3')

    if [ -z "$cadena" ]; then
        echo "Error no existeix vlan $1"
    else
        if iptables -C "$cadena" -j Mode_forward_aillar 2> /dev/null; then
            echo "AÏLLADA"
        elif [ $num_rules -eq 0 ]; then
            echo "CONNECTADA"
        elif  echo "$first_rule" | grep -q "DROP.*0.0.0.0/0.*0.0.0.0/0"; then
            echo "DESCONNECTADA"
        else
            echo "REGLES PROPIES"
        fi
    fi
}

######################################################################
###  MAIN
######################################################################

MSG="falta [iniciar, aturar, configurar ,estat]"

# Comprovem que hi hagi almenys un argument (la opció)
if [ $# -lt 1 ]; then
    echo "$MSG"
    exit 1
fi

OPCIO_1=$1
shift

# Fem switch per executar la funció que toca
case "$OPCIO_1" in
    iniciar)
        fnc_iniciar $@
        ;;
    aturar)
        fnc_aturar $@
        ;;
    configurar)
        fnc_configurar $@
        ;;
    mostrar)
        fnc_mostrar $@
        ;;
    estat)
        fnc_estat $@
        ;;
    *)
        echo "$MSG"
        ;;
esac
